# Generated by Django 5.1.2 on 2024-11-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YouTubeToken',
            new_name='Youtube_token',
        ),
    ]
